#ifndef LB_BASE_STORAGE_DATABASE_PCH_H
#define LB_BASE_STORAGE_DATABASE_PCH_H

#include "../../pch.h"

BEGIN_NAMESPACE_BASE_STORAGE_DATABASE

class DataBase {
   
};

END_NAMESPACE_BASE_STORAGE_DATABASE

#endif /* LB_BASE_STORAGE_DATABASE_PCH_H */
